/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.client.extension.uad.exporter;

import com.liferay.client.extension.model.ClientExtensionEntry;
import com.liferay.client.extension.service.ClientExtensionEntryLocalService;
import com.liferay.client.extension.uad.constants.ClientExtensionUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.xml.Document;
import com.liferay.portal.kernel.xml.Element;
import com.liferay.portal.kernel.xml.SAXReaderUtil;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import java.io.IOException;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the client extension entry UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link ClientExtensionEntryUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseClientExtensionEntryUADExporter
	extends DynamicQueryUADExporter<ClientExtensionEntry> {

	@Override
	public Class<ClientExtensionEntry> getTypeClass() {
		return ClientExtensionEntry.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return clientExtensionEntryLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return ClientExtensionUADConstants.
			USER_ID_FIELD_NAMES_CLIENT_EXTENSION_ENTRY;
	}

	@Override
	protected String toXmlString(ClientExtensionEntry clientExtensionEntry)
		throws IOException {

		Document document = SAXReaderUtil.createDocument();

		Element modelElement = document.addElement("model");
		Element modelNameElement = document.addElement("model-name");

		modelNameElement.addText(
			"com.liferay.client.extension.model.ClientExtensionEntry");

		Element columnElement = modelElement.addElement("column");
		Element columnNameElement = columnElement.addElement("column-name");
		Element columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("clientExtensionEntryId");
		columnValueElement.addText(
			String.valueOf(clientExtensionEntry.getClientExtensionEntryId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("statusByUserId");
		columnValueElement.addText(
			String.valueOf(clientExtensionEntry.getStatusByUserId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("statusByUserName");
		columnValueElement.addCDATA(clientExtensionEntry.getStatusByUserName());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("userId");
		columnValueElement.addText(
			String.valueOf(clientExtensionEntry.getUserId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("userName");
		columnValueElement.addCDATA(clientExtensionEntry.getUserName());

		return document.formattedString();
	}

	@Reference
	protected ClientExtensionEntryLocalService clientExtensionEntryLocalService;

}