/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.blogs.uad.exporter;

import com.liferay.blogs.model.BlogsEntry;
import com.liferay.blogs.service.BlogsEntryLocalService;
import com.liferay.blogs.uad.constants.BlogsUADConstants;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the blogs entry UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link BlogsEntryUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseBlogsEntryUADExporter
	extends DynamicQueryUADExporter<BlogsEntry> {

	@Override
	public Class<BlogsEntry> getTypeClass() {
		return BlogsEntry.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return blogsEntryLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return BlogsUADConstants.USER_ID_FIELD_NAMES_BLOGS_ENTRY;
	}

	@Override
	protected String toXmlString(BlogsEntry blogsEntry) {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.liferay.blogs.model.BlogsEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>entryId</column-name><column-value><![CDATA[");

		String entryId = String.valueOf(blogsEntry.getEntryId());

		entryId = StringUtil.replace(entryId, "]]><", "[$SPECIAL_CHARACTER$]");
		entryId = StringUtil.replace(entryId, "]]>", "]]]]><![CDATA[>");
		entryId = StringUtil.replace(entryId, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(entryId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");

		String statusByUserId = String.valueOf(blogsEntry.getStatusByUserId());

		statusByUserId = StringUtil.replace(
			statusByUserId, "]]><", "[$SPECIAL_CHARACTER$]");
		statusByUserId = StringUtil.replace(
			statusByUserId, "]]>", "]]]]><![CDATA[>");
		statusByUserId = StringUtil.replace(
			statusByUserId, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(statusByUserId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");

		String statusByUserName = String.valueOf(
			blogsEntry.getStatusByUserName());

		statusByUserName = StringUtil.replace(
			statusByUserName, "]]><", "[$SPECIAL_CHARACTER$]");
		statusByUserName = StringUtil.replace(
			statusByUserName, "]]>", "]]]]><![CDATA[>");
		statusByUserName = StringUtil.replace(
			statusByUserName, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(statusByUserName);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");

		String userId = String.valueOf(blogsEntry.getUserId());

		userId = StringUtil.replace(userId, "]]><", "[$SPECIAL_CHARACTER$]");
		userId = StringUtil.replace(userId, "]]>", "]]]]><![CDATA[>");
		userId = StringUtil.replace(userId, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(userId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");

		String userName = String.valueOf(blogsEntry.getUserName());

		userName = StringUtil.replace(
			userName, "]]><", "[$SPECIAL_CHARACTER$]");
		userName = StringUtil.replace(userName, "]]>", "]]]]><![CDATA[>");
		userName = StringUtil.replace(
			userName, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(userName);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");

		String title = String.valueOf(blogsEntry.getTitle());

		title = StringUtil.replace(title, "]]><", "[$SPECIAL_CHARACTER$]");
		title = StringUtil.replace(title, "]]>", "]]]]><![CDATA[>");
		title = StringUtil.replace(title, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(title);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subtitle</column-name><column-value><![CDATA[");

		String subtitle = String.valueOf(blogsEntry.getSubtitle());

		subtitle = StringUtil.replace(
			subtitle, "]]><", "[$SPECIAL_CHARACTER$]");
		subtitle = StringUtil.replace(subtitle, "]]>", "]]]]><![CDATA[>");
		subtitle = StringUtil.replace(
			subtitle, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(subtitle);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>urlTitle</column-name><column-value><![CDATA[");

		String urlTitle = String.valueOf(blogsEntry.getUrlTitle());

		urlTitle = StringUtil.replace(
			urlTitle, "]]><", "[$SPECIAL_CHARACTER$]");
		urlTitle = StringUtil.replace(urlTitle, "]]>", "]]]]><![CDATA[>");
		urlTitle = StringUtil.replace(
			urlTitle, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(urlTitle);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");

		String description = String.valueOf(blogsEntry.getDescription());

		description = StringUtil.replace(
			description, "]]><", "[$SPECIAL_CHARACTER$]");
		description = StringUtil.replace(description, "]]>", "]]]]><![CDATA[>");
		description = StringUtil.replace(
			description, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(description);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");

		String content = String.valueOf(blogsEntry.getContent());

		content = StringUtil.replace(content, "]]><", "[$SPECIAL_CHARACTER$]");
		content = StringUtil.replace(content, "]]>", "]]]]><![CDATA[>");
		content = StringUtil.replace(content, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(content);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>smallImage</column-name><column-value><![CDATA[");

		String smallImage = String.valueOf(blogsEntry.getSmallImage());

		smallImage = StringUtil.replace(
			smallImage, "]]><", "[$SPECIAL_CHARACTER$]");
		smallImage = StringUtil.replace(smallImage, "]]>", "]]]]><![CDATA[>");
		smallImage = StringUtil.replace(
			smallImage, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(smallImage);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>smallImageId</column-name><column-value><![CDATA[");

		String smallImageId = String.valueOf(blogsEntry.getSmallImageId());

		smallImageId = StringUtil.replace(
			smallImageId, "]]><", "[$SPECIAL_CHARACTER$]");
		smallImageId = StringUtil.replace(
			smallImageId, "]]>", "]]]]><![CDATA[>");
		smallImageId = StringUtil.replace(
			smallImageId, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(smallImageId);

		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected BlogsEntryLocalService blogsEntryLocalService;

}