/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.PermissionPropagation;
import com.liferay.portal.kernel.model.PermissionPropagationModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PermissionPropagation service. Represents a row in the &quot;PermissionPropagation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PermissionPropagationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PermissionPropagationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermissionPropagationImpl
 * @generated
 */
public class PermissionPropagationModelImpl
	extends BaseModelImpl<PermissionPropagation>
	implements PermissionPropagationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a permission propagation model instance should use the <code>PermissionPropagation</code> interface instead.
	 */
	public static final String TABLE_NAME = "PermissionPropagation";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"permissionPropagationId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"propagate", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("permissionPropagationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propagate", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PermissionPropagation (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,permissionPropagationId LONG not null,groupId LONG,companyId LONG,classNameId LONG,classPK LONG,propagate BOOLEAN,primary key (permissionPropagationId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table PermissionPropagation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY permissionPropagation.permissionPropagationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PermissionPropagation.permissionPropagationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PERMISSIONPROPAGATIONID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.util.PropsUtil.get(
			"lock.expiration.time.com.liferay.portal.kernel.model.PermissionPropagation"));

	public PermissionPropagationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _permissionPropagationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPermissionPropagationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _permissionPropagationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PermissionPropagation.class;
	}

	@Override
	public String getModelClassName() {
		return PermissionPropagation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PermissionPropagation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PermissionPropagation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PermissionPropagation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PermissionPropagation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PermissionPropagation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PermissionPropagation, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PermissionPropagation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PermissionPropagation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PermissionPropagation, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<PermissionPropagation, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<PermissionPropagation, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<PermissionPropagation, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", PermissionPropagation::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", PermissionPropagation::getCtCollectionId);
			attributeGetterFunctions.put(
				"permissionPropagationId",
				PermissionPropagation::getPermissionPropagationId);
			attributeGetterFunctions.put(
				"groupId", PermissionPropagation::getGroupId);
			attributeGetterFunctions.put(
				"companyId", PermissionPropagation::getCompanyId);
			attributeGetterFunctions.put(
				"classNameId", PermissionPropagation::getClassNameId);
			attributeGetterFunctions.put(
				"classPK", PermissionPropagation::getClassPK);
			attributeGetterFunctions.put(
				"propagate", PermissionPropagation::getPropagate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<PermissionPropagation, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PermissionPropagation, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<PermissionPropagation, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<PermissionPropagation, Long>)
					PermissionPropagation::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<PermissionPropagation, Long>)
					PermissionPropagation::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"permissionPropagationId",
				(BiConsumer<PermissionPropagation, Long>)
					PermissionPropagation::setPermissionPropagationId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<PermissionPropagation, Long>)
					PermissionPropagation::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PermissionPropagation, Long>)
					PermissionPropagation::setCompanyId);
			attributeSetterBiConsumers.put(
				"classNameId",
				(BiConsumer<PermissionPropagation, Long>)
					PermissionPropagation::setClassNameId);
			attributeSetterBiConsumers.put(
				"classPK",
				(BiConsumer<PermissionPropagation, Long>)
					PermissionPropagation::setClassPK);
			attributeSetterBiConsumers.put(
				"propagate",
				(BiConsumer<PermissionPropagation, Boolean>)
					PermissionPropagation::setPropagate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public long getPermissionPropagationId() {
		return _permissionPropagationId;
	}

	@Override
	public void setPermissionPropagationId(long permissionPropagationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_permissionPropagationId = permissionPropagationId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	@Override
	public boolean getPropagate() {
		return _propagate;
	}

	@Override
	public boolean isPropagate() {
		return _propagate;
	}

	@Override
	public void setPropagate(boolean propagate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propagate = propagate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PermissionPropagation.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PermissionPropagation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PermissionPropagation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PermissionPropagationImpl permissionPropagationImpl =
			new PermissionPropagationImpl();

		permissionPropagationImpl.setMvccVersion(getMvccVersion());
		permissionPropagationImpl.setCtCollectionId(getCtCollectionId());
		permissionPropagationImpl.setPermissionPropagationId(
			getPermissionPropagationId());
		permissionPropagationImpl.setGroupId(getGroupId());
		permissionPropagationImpl.setCompanyId(getCompanyId());
		permissionPropagationImpl.setClassNameId(getClassNameId());
		permissionPropagationImpl.setClassPK(getClassPK());
		permissionPropagationImpl.setPropagate(isPropagate());

		permissionPropagationImpl.resetOriginalValues();

		return permissionPropagationImpl;
	}

	@Override
	public PermissionPropagation cloneWithOriginalValues() {
		PermissionPropagationImpl permissionPropagationImpl =
			new PermissionPropagationImpl();

		permissionPropagationImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		permissionPropagationImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		permissionPropagationImpl.setPermissionPropagationId(
			this.<Long>getColumnOriginalValue("permissionPropagationId"));
		permissionPropagationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		permissionPropagationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		permissionPropagationImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		permissionPropagationImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));
		permissionPropagationImpl.setPropagate(
			this.<Boolean>getColumnOriginalValue("propagate"));

		return permissionPropagationImpl;
	}

	@Override
	public int compareTo(PermissionPropagation permissionPropagation) {
		long primaryKey = permissionPropagation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PermissionPropagation)) {
			return false;
		}

		PermissionPropagation permissionPropagation =
			(PermissionPropagation)object;

		long primaryKey = permissionPropagation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PermissionPropagation> toCacheModel() {
		PermissionPropagationCacheModel permissionPropagationCacheModel =
			new PermissionPropagationCacheModel();

		permissionPropagationCacheModel.mvccVersion = getMvccVersion();

		permissionPropagationCacheModel.ctCollectionId = getCtCollectionId();

		permissionPropagationCacheModel.permissionPropagationId =
			getPermissionPropagationId();

		permissionPropagationCacheModel.groupId = getGroupId();

		permissionPropagationCacheModel.companyId = getCompanyId();

		permissionPropagationCacheModel.classNameId = getClassNameId();

		permissionPropagationCacheModel.classPK = getClassPK();

		permissionPropagationCacheModel.propagate = isPropagate();

		return permissionPropagationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PermissionPropagation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PermissionPropagation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PermissionPropagation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PermissionPropagation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PermissionPropagation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PermissionPropagation.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _permissionPropagationId;
	private long _groupId;
	private long _companyId;
	private long _classNameId;
	private long _classPK;
	private boolean _propagate;

	public <T> T getColumnValue(String columnName) {
		Function<PermissionPropagation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PermissionPropagation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put(
			"permissionPropagationId", _permissionPropagationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put("propagate", _propagate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("permissionPropagationId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("classNameId", 32L);

		columnBitmasks.put("classPK", 64L);

		columnBitmasks.put("propagate", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PermissionPropagation _escapedModel;

}