/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.kernel.model;

import com.liferay.portal.kernel.model.change.tracking.CTModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PermissionPropagation service. Represents a row in the &quot;PermissionPropagation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.model.impl.PermissionPropagationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.model.impl.PermissionPropagationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermissionPropagation
 * @generated
 */
@ProviderType
public interface PermissionPropagationModel
	extends AttachedModel, BaseModel<PermissionPropagation>,
			CTModel<PermissionPropagation>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a permission propagation model instance should use the {@link PermissionPropagation} interface instead.
	 */

	/**
	 * Returns the primary key of this permission propagation.
	 *
	 * @return the primary key of this permission propagation
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this permission propagation.
	 *
	 * @param primaryKey the primary key of this permission propagation
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this permission propagation.
	 *
	 * @return the mvcc version of this permission propagation
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this permission propagation.
	 *
	 * @param mvccVersion the mvcc version of this permission propagation
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this permission propagation.
	 *
	 * @return the ct collection ID of this permission propagation
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this permission propagation.
	 *
	 * @param ctCollectionId the ct collection ID of this permission propagation
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the permission propagation ID of this permission propagation.
	 *
	 * @return the permission propagation ID of this permission propagation
	 */
	public long getPermissionPropagationId();

	/**
	 * Sets the permission propagation ID of this permission propagation.
	 *
	 * @param permissionPropagationId the permission propagation ID of this permission propagation
	 */
	public void setPermissionPropagationId(long permissionPropagationId);

	/**
	 * Returns the group ID of this permission propagation.
	 *
	 * @return the group ID of this permission propagation
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this permission propagation.
	 *
	 * @param groupId the group ID of this permission propagation
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this permission propagation.
	 *
	 * @return the company ID of this permission propagation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this permission propagation.
	 *
	 * @param companyId the company ID of this permission propagation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the fully qualified class name of this permission propagation.
	 *
	 * @return the fully qualified class name of this permission propagation
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this permission propagation.
	 *
	 * @return the class name ID of this permission propagation
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this permission propagation.
	 *
	 * @param classNameId the class name ID of this permission propagation
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this permission propagation.
	 *
	 * @return the class pk of this permission propagation
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this permission propagation.
	 *
	 * @param classPK the class pk of this permission propagation
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the propagate of this permission propagation.
	 *
	 * @return the propagate of this permission propagation
	 */
	public boolean getPropagate();

	/**
	 * Returns <code>true</code> if this permission propagation is propagate.
	 *
	 * @return <code>true</code> if this permission propagation is propagate; <code>false</code> otherwise
	 */
	public boolean isPropagate();

	/**
	 * Sets whether this permission propagation is propagate.
	 *
	 * @param propagate the propagate of this permission propagation
	 */
	public void setPropagate(boolean propagate);

	@Override
	public PermissionPropagation cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}