/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.BadColumnNameEntry;
import com.liferay.portal.tools.service.builder.test.service.BadColumnNameEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.BadColumnNameEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.BadColumnNameEntryPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the bad column name entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.BadColumnNameEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.BadColumnNameEntryLocalServiceImpl
 * @generated
 */
public abstract class BadColumnNameEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements BadColumnNameEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>BadColumnNameEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>BadColumnNameEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the bad column name entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BadColumnNameEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param badColumnNameEntry the bad column name entry
	 * @return the bad column name entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BadColumnNameEntry addBadColumnNameEntry(
		BadColumnNameEntry badColumnNameEntry) {

		badColumnNameEntry.setNew(true);

		return badColumnNameEntryPersistence.update(badColumnNameEntry);
	}

	/**
	 * Creates a new bad column name entry with the primary key. Does not add the bad column name entry to the database.
	 *
	 * @param badColumnNameEntryId the primary key for the new bad column name entry
	 * @return the new bad column name entry
	 */
	@Override
	@Transactional(enabled = false)
	public BadColumnNameEntry createBadColumnNameEntry(
		long badColumnNameEntryId) {

		return badColumnNameEntryPersistence.create(badColumnNameEntryId);
	}

	/**
	 * Deletes the bad column name entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BadColumnNameEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param badColumnNameEntryId the primary key of the bad column name entry
	 * @return the bad column name entry that was removed
	 * @throws PortalException if a bad column name entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BadColumnNameEntry deleteBadColumnNameEntry(
			long badColumnNameEntryId)
		throws PortalException {

		return badColumnNameEntryPersistence.remove(badColumnNameEntryId);
	}

	/**
	 * Deletes the bad column name entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BadColumnNameEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param badColumnNameEntry the bad column name entry
	 * @return the bad column name entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BadColumnNameEntry deleteBadColumnNameEntry(
		BadColumnNameEntry badColumnNameEntry) {

		return badColumnNameEntryPersistence.remove(badColumnNameEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return badColumnNameEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			BadColumnNameEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return badColumnNameEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.BadColumnNameEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return badColumnNameEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.BadColumnNameEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return badColumnNameEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return badColumnNameEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return badColumnNameEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public BadColumnNameEntry fetchBadColumnNameEntry(
		long badColumnNameEntryId) {

		return badColumnNameEntryPersistence.fetchByPrimaryKey(
			badColumnNameEntryId);
	}

	/**
	 * Returns the bad column name entry with the primary key.
	 *
	 * @param badColumnNameEntryId the primary key of the bad column name entry
	 * @return the bad column name entry
	 * @throws PortalException if a bad column name entry with the primary key could not be found
	 */
	@Override
	public BadColumnNameEntry getBadColumnNameEntry(long badColumnNameEntryId)
		throws PortalException {

		return badColumnNameEntryPersistence.findByPrimaryKey(
			badColumnNameEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			badColumnNameEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BadColumnNameEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"badColumnNameEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			badColumnNameEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(BadColumnNameEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"badColumnNameEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			badColumnNameEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BadColumnNameEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"badColumnNameEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return badColumnNameEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement BadColumnNameEntryLocalServiceImpl#deleteBadColumnNameEntry(BadColumnNameEntry) to avoid orphaned data");
		}

		return badColumnNameEntryLocalService.deleteBadColumnNameEntry(
			(BadColumnNameEntry)persistedModel);
	}

	@Override
	public BasePersistence<BadColumnNameEntry> getBasePersistence() {
		return badColumnNameEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return badColumnNameEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the bad column name entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.BadColumnNameEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of bad column name entries
	 * @param end the upper bound of the range of bad column name entries (not inclusive)
	 * @return the range of bad column name entries
	 */
	@Override
	public List<BadColumnNameEntry> getBadColumnNameEntries(
		int start, int end) {

		return badColumnNameEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of bad column name entries.
	 *
	 * @return the number of bad column name entries
	 */
	@Override
	public int getBadColumnNameEntriesCount() {
		return badColumnNameEntryPersistence.countAll();
	}

	/**
	 * Updates the bad column name entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BadColumnNameEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param badColumnNameEntry the bad column name entry
	 * @return the bad column name entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BadColumnNameEntry updateBadColumnNameEntry(
		BadColumnNameEntry badColumnNameEntry) {

		return badColumnNameEntryPersistence.update(badColumnNameEntry);
	}

	/**
	 * Returns the bad column name entry local service.
	 *
	 * @return the bad column name entry local service
	 */
	public BadColumnNameEntryLocalService getBadColumnNameEntryLocalService() {
		return badColumnNameEntryLocalService;
	}

	/**
	 * Sets the bad column name entry local service.
	 *
	 * @param badColumnNameEntryLocalService the bad column name entry local service
	 */
	public void setBadColumnNameEntryLocalService(
		BadColumnNameEntryLocalService badColumnNameEntryLocalService) {

		this.badColumnNameEntryLocalService = badColumnNameEntryLocalService;
	}

	/**
	 * Returns the bad column name entry persistence.
	 *
	 * @return the bad column name entry persistence
	 */
	public BadColumnNameEntryPersistence getBadColumnNameEntryPersistence() {
		return badColumnNameEntryPersistence;
	}

	/**
	 * Sets the bad column name entry persistence.
	 *
	 * @param badColumnNameEntryPersistence the bad column name entry persistence
	 */
	public void setBadColumnNameEntryPersistence(
		BadColumnNameEntryPersistence badColumnNameEntryPersistence) {

		this.badColumnNameEntryPersistence = badColumnNameEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		BadColumnNameEntryLocalServiceUtil.setService(
			badColumnNameEntryLocalService);
	}

	public void destroy() {
		BadColumnNameEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BadColumnNameEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return BadColumnNameEntry.class;
	}

	protected String getModelClassName() {
		return BadColumnNameEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				badColumnNameEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = BadColumnNameEntryLocalService.class)
	protected BadColumnNameEntryLocalService badColumnNameEntryLocalService;

	@BeanReference(type = BadColumnNameEntryPersistence.class)
	protected BadColumnNameEntryPersistence badColumnNameEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		BadColumnNameEntryLocalServiceBaseImpl.class);

}