/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.FilterPrimaryEntry;
import com.liferay.portal.tools.service.builder.test.service.FilterPrimaryEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.FilterPrimaryEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.FilterPrimaryEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the filter primary entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.FilterPrimaryEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.FilterPrimaryEntryLocalServiceImpl
 * @generated
 */
public abstract class FilterPrimaryEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements FilterPrimaryEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FilterPrimaryEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FilterPrimaryEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the filter primary entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FilterPrimaryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param filterPrimaryEntry the filter primary entry
	 * @return the filter primary entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FilterPrimaryEntry addFilterPrimaryEntry(
		FilterPrimaryEntry filterPrimaryEntry) {

		filterPrimaryEntry.setNew(true);

		return filterPrimaryEntryPersistence.update(filterPrimaryEntry);
	}

	/**
	 * Creates a new filter primary entry with the primary key. Does not add the filter primary entry to the database.
	 *
	 * @param filterPrimaryEntryId the primary key for the new filter primary entry
	 * @return the new filter primary entry
	 */
	@Override
	@Transactional(enabled = false)
	public FilterPrimaryEntry createFilterPrimaryEntry(
		long filterPrimaryEntryId) {

		return filterPrimaryEntryPersistence.create(filterPrimaryEntryId);
	}

	/**
	 * Deletes the filter primary entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FilterPrimaryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param filterPrimaryEntryId the primary key of the filter primary entry
	 * @return the filter primary entry that was removed
	 * @throws PortalException if a filter primary entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FilterPrimaryEntry deleteFilterPrimaryEntry(
			long filterPrimaryEntryId)
		throws PortalException {

		return filterPrimaryEntryPersistence.remove(filterPrimaryEntryId);
	}

	/**
	 * Deletes the filter primary entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FilterPrimaryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param filterPrimaryEntry the filter primary entry
	 * @return the filter primary entry that was removed
	 * @throws PortalException
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FilterPrimaryEntry deleteFilterPrimaryEntry(
			FilterPrimaryEntry filterPrimaryEntry)
		throws PortalException {

		return filterPrimaryEntryPersistence.remove(filterPrimaryEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return filterPrimaryEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FilterPrimaryEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return filterPrimaryEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.FilterPrimaryEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return filterPrimaryEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.FilterPrimaryEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return filterPrimaryEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return filterPrimaryEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return filterPrimaryEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FilterPrimaryEntry fetchFilterPrimaryEntry(
		long filterPrimaryEntryId) {

		return filterPrimaryEntryPersistence.fetchByPrimaryKey(
			filterPrimaryEntryId);
	}

	/**
	 * Returns the filter primary entry with the primary key.
	 *
	 * @param filterPrimaryEntryId the primary key of the filter primary entry
	 * @return the filter primary entry
	 * @throws PortalException if a filter primary entry with the primary key could not be found
	 */
	@Override
	public FilterPrimaryEntry getFilterPrimaryEntry(long filterPrimaryEntryId)
		throws PortalException {

		return filterPrimaryEntryPersistence.findByPrimaryKey(
			filterPrimaryEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			filterPrimaryEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FilterPrimaryEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"filterPrimaryEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			filterPrimaryEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(FilterPrimaryEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"filterPrimaryEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			filterPrimaryEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FilterPrimaryEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"filterPrimaryEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return filterPrimaryEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement FilterPrimaryEntryLocalServiceImpl#deleteFilterPrimaryEntry(FilterPrimaryEntry) to avoid orphaned data");
		}

		return filterPrimaryEntryLocalService.deleteFilterPrimaryEntry(
			(FilterPrimaryEntry)persistedModel);
	}

	@Override
	public BasePersistence<FilterPrimaryEntry> getBasePersistence() {
		return filterPrimaryEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return filterPrimaryEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	@Override
	public List<? extends PersistedModel> getPersistedModel(
			long resourcePrimKey)
		throws PortalException {

		return filterPrimaryEntryPersistence.findByResourcePrimKey(
			resourcePrimKey);
	}

	/**
	 * Returns a range of all the filter primary entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.FilterPrimaryEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of filter primary entries
	 * @param end the upper bound of the range of filter primary entries (not inclusive)
	 * @return the range of filter primary entries
	 */
	@Override
	public List<FilterPrimaryEntry> getFilterPrimaryEntries(
		int start, int end) {

		return filterPrimaryEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of filter primary entries.
	 *
	 * @return the number of filter primary entries
	 */
	@Override
	public int getFilterPrimaryEntriesCount() {
		return filterPrimaryEntryPersistence.countAll();
	}

	/**
	 * Updates the filter primary entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FilterPrimaryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param filterPrimaryEntry the filter primary entry
	 * @return the filter primary entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FilterPrimaryEntry updateFilterPrimaryEntry(
		FilterPrimaryEntry filterPrimaryEntry) {

		return filterPrimaryEntryPersistence.update(filterPrimaryEntry);
	}

	/**
	 * Returns the filter primary entry local service.
	 *
	 * @return the filter primary entry local service
	 */
	public FilterPrimaryEntryLocalService getFilterPrimaryEntryLocalService() {
		return filterPrimaryEntryLocalService;
	}

	/**
	 * Sets the filter primary entry local service.
	 *
	 * @param filterPrimaryEntryLocalService the filter primary entry local service
	 */
	public void setFilterPrimaryEntryLocalService(
		FilterPrimaryEntryLocalService filterPrimaryEntryLocalService) {

		this.filterPrimaryEntryLocalService = filterPrimaryEntryLocalService;
	}

	/**
	 * Returns the filter primary entry persistence.
	 *
	 * @return the filter primary entry persistence
	 */
	public FilterPrimaryEntryPersistence getFilterPrimaryEntryPersistence() {
		return filterPrimaryEntryPersistence;
	}

	/**
	 * Sets the filter primary entry persistence.
	 *
	 * @param filterPrimaryEntryPersistence the filter primary entry persistence
	 */
	public void setFilterPrimaryEntryPersistence(
		FilterPrimaryEntryPersistence filterPrimaryEntryPersistence) {

		this.filterPrimaryEntryPersistence = filterPrimaryEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		FilterPrimaryEntryLocalServiceUtil.setService(
			filterPrimaryEntryLocalService);
	}

	public void destroy() {
		FilterPrimaryEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FilterPrimaryEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FilterPrimaryEntry.class;
	}

	protected String getModelClassName() {
		return FilterPrimaryEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = filterPrimaryEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = FilterPrimaryEntryLocalService.class)
	protected FilterPrimaryEntryLocalService filterPrimaryEntryLocalService;

	@BeanReference(type = FilterPrimaryEntryPersistence.class)
	protected FilterPrimaryEntryPersistence filterPrimaryEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		FilterPrimaryEntryLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:-1035879015