/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.SequenceEntry;
import com.liferay.portal.tools.service.builder.test.service.SequenceEntryService;
import com.liferay.portal.tools.service.builder.test.service.SequenceEntryServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.SequenceEntryPersistence;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the sequence entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.SequenceEntryServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.SequenceEntryServiceImpl
 * @generated
 */
public abstract class SequenceEntryServiceBaseImpl
	extends BaseServiceImpl
	implements IdentifiableOSGiService, SequenceEntryService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SequenceEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>SequenceEntryServiceUtil</code>.
	 */

	/**
	 * Returns the sequence entry local service.
	 *
	 * @return the sequence entry local service
	 */
	public com.liferay.portal.tools.service.builder.test.service.
		SequenceEntryLocalService getSequenceEntryLocalService() {

		return sequenceEntryLocalService;
	}

	/**
	 * Sets the sequence entry local service.
	 *
	 * @param sequenceEntryLocalService the sequence entry local service
	 */
	public void setSequenceEntryLocalService(
		com.liferay.portal.tools.service.builder.test.service.
			SequenceEntryLocalService sequenceEntryLocalService) {

		this.sequenceEntryLocalService = sequenceEntryLocalService;
	}

	/**
	 * Returns the sequence entry remote service.
	 *
	 * @return the sequence entry remote service
	 */
	public SequenceEntryService getSequenceEntryService() {
		return sequenceEntryService;
	}

	/**
	 * Sets the sequence entry remote service.
	 *
	 * @param sequenceEntryService the sequence entry remote service
	 */
	public void setSequenceEntryService(
		SequenceEntryService sequenceEntryService) {

		this.sequenceEntryService = sequenceEntryService;
	}

	/**
	 * Returns the sequence entry persistence.
	 *
	 * @return the sequence entry persistence
	 */
	public SequenceEntryPersistence getSequenceEntryPersistence() {
		return sequenceEntryPersistence;
	}

	/**
	 * Sets the sequence entry persistence.
	 *
	 * @param sequenceEntryPersistence the sequence entry persistence
	 */
	public void setSequenceEntryPersistence(
		SequenceEntryPersistence sequenceEntryPersistence) {

		this.sequenceEntryPersistence = sequenceEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(sequenceEntryService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SequenceEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SequenceEntry.class;
	}

	protected String getModelClassName() {
		return SequenceEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = sequenceEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		SequenceEntryService sequenceEntryService) {

		try {
			Field field = SequenceEntryServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, sequenceEntryService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.portal.tools.service.builder.test.service.SequenceEntryLocalService.class
	)
	protected com.liferay.portal.tools.service.builder.test.service.
		SequenceEntryLocalService sequenceEntryLocalService;

	@BeanReference(type = SequenceEntryService.class)
	protected SequenceEntryService sequenceEntryService;

	@BeanReference(type = SequenceEntryPersistence.class)
	protected SequenceEntryPersistence sequenceEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		SequenceEntryServiceBaseImpl.class);

}