/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BadColumnNameEntry service. Represents a row in the &quot;BadColumnNameEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.BadColumnNameEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.BadColumnNameEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BadColumnNameEntry
 * @generated
 */
@ProviderType
public interface BadColumnNameEntryModel extends BaseModel<BadColumnNameEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bad column name entry model instance should use the {@link BadColumnNameEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this bad column name entry.
	 *
	 * @return the primary key of this bad column name entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bad column name entry.
	 *
	 * @param primaryKey the primary key of this bad column name entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bad column name entry ID of this bad column name entry.
	 *
	 * @return the bad column name entry ID of this bad column name entry
	 */
	public long getBadColumnNameEntryId();

	/**
	 * Sets the bad column name entry ID of this bad column name entry.
	 *
	 * @param badColumnNameEntryId the bad column name entry ID of this bad column name entry
	 */
	public void setBadColumnNameEntryId(long badColumnNameEntryId);

	/**
	 * Returns the type of this bad column name entry.
	 *
	 * @return the type of this bad column name entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this bad column name entry.
	 *
	 * @param type the type of this bad column name entry
	 */
	public void setType(String type);

	@Override
	public BadColumnNameEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}