/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DateTypeEntry service. Represents a row in the &quot;DateTypeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.DateTypeEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.DateTypeEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DateTypeEntry
 * @generated
 */
@ProviderType
public interface DateTypeEntryModel extends BaseModel<DateTypeEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a date type entry model instance should use the {@link DateTypeEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this date type entry.
	 *
	 * @return the primary key of this date type entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this date type entry.
	 *
	 * @param primaryKey the primary key of this date type entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the date type entry ID of this date type entry.
	 *
	 * @return the date type entry ID of this date type entry
	 */
	public long getDateTypeEntryId();

	/**
	 * Sets the date type entry ID of this date type entry.
	 *
	 * @param dateTypeEntryId the date type entry ID of this date type entry
	 */
	public void setDateTypeEntryId(long dateTypeEntryId);

	/**
	 * Returns the date value of this date type entry.
	 *
	 * @return the date value of this date type entry
	 */
	public Date getDateValue();

	/**
	 * Sets the date value of this date type entry.
	 *
	 * @param dateValue the date value of this date type entry
	 */
	public void setDateValue(Date dateValue);

	@Override
	public DateTypeEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1321870086