/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.math.BigDecimal;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DSLQueryEntry service. Represents a row in the &quot;DSLQueryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.DSLQueryEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.DSLQueryEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DSLQueryEntry
 * @generated
 */
@ProviderType
public interface DSLQueryEntryModel extends BaseModel<DSLQueryEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dsl query entry model instance should use the {@link DSLQueryEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this dsl query entry.
	 *
	 * @return the primary key of this dsl query entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dsl query entry.
	 *
	 * @param primaryKey the primary key of this dsl query entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dsl query entry ID of this dsl query entry.
	 *
	 * @return the dsl query entry ID of this dsl query entry
	 */
	public long getDslQueryEntryId();

	/**
	 * Sets the dsl query entry ID of this dsl query entry.
	 *
	 * @param dslQueryEntryId the dsl query entry ID of this dsl query entry
	 */
	public void setDslQueryEntryId(long dslQueryEntryId);

	/**
	 * Returns the name of this dsl query entry.
	 *
	 * @return the name of this dsl query entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dsl query entry.
	 *
	 * @param name the name of this dsl query entry
	 */
	public void setName(String name);

	/**
	 * Returns the big decimal value of this dsl query entry.
	 *
	 * @return the big decimal value of this dsl query entry
	 */
	public BigDecimal getBigDecimalValue();

	/**
	 * Sets the big decimal value of this dsl query entry.
	 *
	 * @param bigDecimalValue the big decimal value of this dsl query entry
	 */
	public void setBigDecimalValue(BigDecimal bigDecimalValue);

	/**
	 * Returns the double value of this dsl query entry.
	 *
	 * @return the double value of this dsl query entry
	 */
	public double getDoubleValue();

	/**
	 * Sets the double value of this dsl query entry.
	 *
	 * @param doubleValue the double value of this dsl query entry
	 */
	public void setDoubleValue(double doubleValue);

	/**
	 * Returns the int value of this dsl query entry.
	 *
	 * @return the int value of this dsl query entry
	 */
	public int getIntValue();

	/**
	 * Sets the int value of this dsl query entry.
	 *
	 * @param intValue the int value of this dsl query entry
	 */
	public void setIntValue(int intValue);

	/**
	 * Returns the long value of this dsl query entry.
	 *
	 * @return the long value of this dsl query entry
	 */
	public long getLongValue();

	/**
	 * Sets the long value of this dsl query entry.
	 *
	 * @param longValue the long value of this dsl query entry
	 */
	public void setLongValue(long longValue);

	@Override
	public DSLQueryEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}