/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FilterFindEntry service. Represents a row in the &quot;FilterFindEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.FilterFindEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.FilterFindEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FilterFindEntry
 * @generated
 */
@ProviderType
public interface FilterFindEntryModel extends BaseModel<FilterFindEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a filter find entry model instance should use the {@link FilterFindEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this filter find entry.
	 *
	 * @return the primary key of this filter find entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this filter find entry.
	 *
	 * @param primaryKey the primary key of this filter find entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the filter find entry ID of this filter find entry.
	 *
	 * @return the filter find entry ID of this filter find entry
	 */
	public long getFilterFindEntryId();

	/**
	 * Sets the filter find entry ID of this filter find entry.
	 *
	 * @param filterFindEntryId the filter find entry ID of this filter find entry
	 */
	public void setFilterFindEntryId(long filterFindEntryId);

	/**
	 * Returns the group ID of this filter find entry.
	 *
	 * @return the group ID of this filter find entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this filter find entry.
	 *
	 * @param groupId the group ID of this filter find entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the type of this filter find entry.
	 *
	 * @return the type of this filter find entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this filter find entry.
	 *
	 * @param type the type of this filter find entry
	 */
	public void setType(String type);

	/**
	 * Returns the integer of this filter find entry.
	 *
	 * @return the integer of this filter find entry
	 */
	public int getInteger();

	/**
	 * Sets the integer of this filter find entry.
	 *
	 * @param integer the integer of this filter find entry
	 */
	public void setInteger(int integer);

	@Override
	public FilterFindEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}