/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ResourcedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FilterPrimaryEntry service. Represents a row in the &quot;FilterPrimaryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.FilterPrimaryEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.FilterPrimaryEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FilterPrimaryEntry
 * @generated
 */
@ProviderType
public interface FilterPrimaryEntryModel
	extends BaseModel<FilterPrimaryEntry>, ResourcedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a filter primary entry model instance should use the {@link FilterPrimaryEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this filter primary entry.
	 *
	 * @return the primary key of this filter primary entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this filter primary entry.
	 *
	 * @param primaryKey the primary key of this filter primary entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the filter primary entry ID of this filter primary entry.
	 *
	 * @return the filter primary entry ID of this filter primary entry
	 */
	public long getFilterPrimaryEntryId();

	/**
	 * Sets the filter primary entry ID of this filter primary entry.
	 *
	 * @param filterPrimaryEntryId the filter primary entry ID of this filter primary entry
	 */
	public void setFilterPrimaryEntryId(long filterPrimaryEntryId);

	/**
	 * Returns the group ID of this filter primary entry.
	 *
	 * @return the group ID of this filter primary entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this filter primary entry.
	 *
	 * @param groupId the group ID of this filter primary entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this filter primary entry.
	 *
	 * @return the company ID of this filter primary entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this filter primary entry.
	 *
	 * @param companyId the company ID of this filter primary entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this filter primary entry.
	 *
	 * @return the user ID of this filter primary entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this filter primary entry.
	 *
	 * @param userId the user ID of this filter primary entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this filter primary entry.
	 *
	 * @return the user uuid of this filter primary entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this filter primary entry.
	 *
	 * @param userUuid the user uuid of this filter primary entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the resource prim key of this filter primary entry.
	 *
	 * @return the resource prim key of this filter primary entry
	 */
	@Override
	public long getResourcePrimKey();

	/**
	 * Sets the resource prim key of this filter primary entry.
	 *
	 * @param resourcePrimKey the resource prim key of this filter primary entry
	 */
	@Override
	public void setResourcePrimKey(long resourcePrimKey);

	@Override
	public boolean isResourceMain();

	@Override
	public FilterPrimaryEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-393154821