/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SequenceEntry service. Represents a row in the &quot;SequenceEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.SequenceEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.SequenceEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SequenceEntry
 * @generated
 */
@ProviderType
public interface SequenceEntryModel extends BaseModel<SequenceEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sequence entry model instance should use the {@link SequenceEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this sequence entry.
	 *
	 * @return the primary key of this sequence entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sequence entry.
	 *
	 * @param primaryKey the primary key of this sequence entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sequence entry.
	 *
	 * @return the uuid of this sequence entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this sequence entry.
	 *
	 * @param uuid the uuid of this sequence entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the sequence entry ID of this sequence entry.
	 *
	 * @return the sequence entry ID of this sequence entry
	 */
	public long getSequenceEntryId();

	/**
	 * Sets the sequence entry ID of this sequence entry.
	 *
	 * @param sequenceEntryId the sequence entry ID of this sequence entry
	 */
	public void setSequenceEntryId(long sequenceEntryId);

	@Override
	public SequenceEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}