/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.message.boards.uad.exporter;

import com.liferay.message.boards.model.MBCategory;
import com.liferay.message.boards.service.MBCategoryLocalService;
import com.liferay.message.boards.uad.constants.MBUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.xml.Document;
import com.liferay.portal.kernel.xml.Element;
import com.liferay.portal.kernel.xml.SAXReaderUtil;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import java.io.IOException;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the message boards category UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link MBCategoryUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseMBCategoryUADExporter
	extends DynamicQueryUADExporter<MBCategory> {

	@Override
	public Class<MBCategory> getTypeClass() {
		return MBCategory.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return mbCategoryLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return MBUADConstants.USER_ID_FIELD_NAMES_MB_CATEGORY;
	}

	@Override
	protected String toXmlString(MBCategory mbCategory) throws IOException {
		Document document = SAXReaderUtil.createDocument();

		Element modelElement = document.addElement("model");
		Element modelNameElement = document.addElement("model-name");

		modelNameElement.addText("com.liferay.message.boards.model.MBCategory");

		Element columnElement = modelElement.addElement("column");
		Element columnNameElement = columnElement.addElement("column-name");
		Element columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("categoryId");
		columnValueElement.addText(String.valueOf(mbCategory.getCategoryId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("statusByUserId");
		columnValueElement.addText(
			String.valueOf(mbCategory.getStatusByUserId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("statusByUserName");
		columnValueElement.addCDATA(mbCategory.getStatusByUserName());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("userId");
		columnValueElement.addText(String.valueOf(mbCategory.getUserId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("userName");
		columnValueElement.addCDATA(mbCategory.getUserName());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("name");
		columnValueElement.addCDATA(mbCategory.getName());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("description");
		columnValueElement.addCDATA(mbCategory.getDescription());

		return document.formattedString();
	}

	@Reference
	protected MBCategoryLocalService mbCategoryLocalService;

}