/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.message.boards.uad.exporter;

import com.liferay.message.boards.model.MBMessage;
import com.liferay.message.boards.service.MBMessageLocalService;
import com.liferay.message.boards.uad.constants.MBUADConstants;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the message-boards message UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link MBMessageUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseMBMessageUADExporter
	extends DynamicQueryUADExporter<MBMessage> {

	@Override
	public Class<MBMessage> getTypeClass() {
		return MBMessage.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return mbMessageLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return MBUADConstants.USER_ID_FIELD_NAMES_MB_MESSAGE;
	}

	@Override
	protected String toXmlString(MBMessage mbMessage) {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.liferay.message.boards.model.MBMessage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>messageId</column-name><column-value><![CDATA[");

		String messageId = String.valueOf(mbMessage.getMessageId());

		sb.append(messageId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");

		String statusByUserId = String.valueOf(mbMessage.getStatusByUserId());

		sb.append(statusByUserId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");

		String statusByUserName = String.valueOf(
			mbMessage.getStatusByUserName());

		statusByUserName = StringUtil.replace(
			statusByUserName, "]]>", "]]]]><![CDATA[>");

		sb.append(statusByUserName);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");

		String userId = String.valueOf(mbMessage.getUserId());

		sb.append(userId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");

		String userName = String.valueOf(mbMessage.getUserName());

		userName = StringUtil.replace(userName, "]]>", "]]]]><![CDATA[>");

		sb.append(userName);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subject</column-name><column-value><![CDATA[");

		String subject = String.valueOf(mbMessage.getSubject());

		subject = StringUtil.replace(subject, "]]>", "]]]]><![CDATA[>");

		sb.append(subject);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>urlSubject</column-name><column-value><![CDATA[");

		String urlSubject = String.valueOf(mbMessage.getUrlSubject());

		urlSubject = StringUtil.replace(urlSubject, "]]>", "]]]]><![CDATA[>");

		sb.append(urlSubject);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>body</column-name><column-value><![CDATA[");

		String body = String.valueOf(mbMessage.getBody());

		body = StringUtil.replace(body, "]]>", "]]]]><![CDATA[>");

		sb.append(body);

		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected MBMessageLocalService mbMessageLocalService;

}