/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.wiki.uad.exporter;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.xml.Document;
import com.liferay.portal.kernel.xml.Element;
import com.liferay.portal.kernel.xml.SAXReaderUtil;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;
import com.liferay.wiki.model.WikiPage;
import com.liferay.wiki.service.WikiPageLocalService;
import com.liferay.wiki.uad.constants.WikiUADConstants;

import java.io.IOException;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the wiki page UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link WikiPageUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseWikiPageUADExporter
	extends DynamicQueryUADExporter<WikiPage> {

	@Override
	public Class<WikiPage> getTypeClass() {
		return WikiPage.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return wikiPageLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return WikiUADConstants.USER_ID_FIELD_NAMES_WIKI_PAGE;
	}

	@Override
	protected String toXmlString(WikiPage wikiPage) throws IOException {
		Document document = SAXReaderUtil.createDocument();

		Element modelElement = document.addElement("model");
		Element modelNameElement = document.addElement("model-name");

		modelNameElement.addText("com.liferay.wiki.model.WikiPage");

		Element columnElement = modelElement.addElement("column");
		Element columnNameElement = columnElement.addElement("column-name");
		Element columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("pageId");
		columnValueElement.addText(String.valueOf(wikiPage.getPageId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("statusByUserId");
		columnValueElement.addText(
			String.valueOf(wikiPage.getStatusByUserId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("statusByUserName");
		columnValueElement.addCDATA(wikiPage.getStatusByUserName());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("userId");
		columnValueElement.addText(String.valueOf(wikiPage.getUserId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("userName");
		columnValueElement.addCDATA(wikiPage.getUserName());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("title");
		columnValueElement.addCDATA(wikiPage.getTitle());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("content");
		columnValueElement.addCDATA(wikiPage.getContent());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("summary");
		columnValueElement.addCDATA(wikiPage.getSummary());

		return document.formattedString();
	}

	@Reference
	protected WikiPageLocalService wikiPageLocalService;

}