dependencies {
	compileInclude group: "org.apache.cxf", name: "cxf-core", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-bindings-soap", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-bindings-xml", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-databinding-jaxb", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-frontend-jaxrs", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-frontend-jaxws", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-frontend-simple", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-rs-client", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-rs-extension-providers", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-rs-json-basic", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-rs-sse", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-security", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-transports-http", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-ws-addr", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-ws-policy", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-rt-wsdl", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-tools-common", version: "3.4.10"
	compileInclude group: "org.apache.cxf", name: "cxf-tools-validator", version: "3.4.10"
	compileInclude group: "org.apache.johnzon", name: "johnzon-core", version: "1.2.21"
	compileInclude group: "org.apache.johnzon", name: "johnzon-jsonb", version: "1.2.21"
	compileInclude group: "org.apache.johnzon", name: "johnzon-mapper", version: "1.2.21"
	compileInclude group: "org.apache.neethi", name: "neethi", version: "3.1.1"
	compileInclude group: "org.apache.velocity", name: "velocity-engine-core", version: "2.2"
	compileInclude group: "org.apache.ws.xmlschema", name: "xmlschema-core", version: "2.2.5"
	compileInclude group: "org.codehaus.jettison", name: "jettison", version: "1.5.4"
	compileInclude group: "org.codehaus.woodstox", name: "stax2-api", version: "4.2.1"
	compileInclude group: "wsdl4j", name: "wsdl4j", version: "1.6.3"

	compileOnly group: "com.fasterxml.woodstox", name: "woodstox-core", version: "6.4.0"
	compileOnly group: "org.apache.geronimo.specs", name: "geronimo-jaxrs_2.1_spec", version: "1.1"
	compileOnly group: "org.apache.geronimo.specs", name: "geronimo-json_1.1_spec", version: "1.5"
	compileOnly group: "org.apache.geronimo.specs", name: "geronimo-jsonb_1.0_spec", version: "1.4"
}