/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bookmarks.uad.exporter;

import com.liferay.bookmarks.model.BookmarksFolder;
import com.liferay.bookmarks.service.BookmarksFolderLocalService;
import com.liferay.bookmarks.uad.constants.BookmarksUADConstants;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the bookmarks folder UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link BookmarksFolderUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseBookmarksFolderUADExporter
	extends DynamicQueryUADExporter<BookmarksFolder> {

	@Override
	public Class<BookmarksFolder> getTypeClass() {
		return BookmarksFolder.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return bookmarksFolderLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return BookmarksUADConstants.USER_ID_FIELD_NAMES_BOOKMARKS_FOLDER;
	}

	@Override
	protected String toXmlString(BookmarksFolder bookmarksFolder) {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.liferay.bookmarks.model.BookmarksFolder");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>folderId</column-name><column-value><![CDATA[");

		String folderId = String.valueOf(bookmarksFolder.getFolderId());

		sb.append(folderId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");

		String statusByUserId = String.valueOf(
			bookmarksFolder.getStatusByUserId());

		sb.append(statusByUserId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");

		String statusByUserName = String.valueOf(
			bookmarksFolder.getStatusByUserName());

		statusByUserName = StringUtil.replace(
			statusByUserName, "]]>", "]]]]><![CDATA[>");

		sb.append(statusByUserName);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");

		String userId = String.valueOf(bookmarksFolder.getUserId());

		sb.append(userId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");

		String userName = String.valueOf(bookmarksFolder.getUserName());

		userName = StringUtil.replace(userName, "]]>", "]]]]><![CDATA[>");

		sb.append(userName);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>treePath</column-name><column-value><![CDATA[");

		String treePath = String.valueOf(bookmarksFolder.getTreePath());

		treePath = StringUtil.replace(treePath, "]]>", "]]]]><![CDATA[>");

		sb.append(treePath);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");

		String name = String.valueOf(bookmarksFolder.getName());

		name = StringUtil.replace(name, "]]>", "]]]]><![CDATA[>");

		sb.append(name);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");

		String description = String.valueOf(bookmarksFolder.getDescription());

		description = StringUtil.replace(description, "]]>", "]]]]><![CDATA[>");

		sb.append(description);

		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected BookmarksFolderLocalService bookmarksFolderLocalService;

}