/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bookmarks.uad.exporter;

import com.liferay.bookmarks.model.BookmarksFolder;
import com.liferay.bookmarks.service.BookmarksFolderLocalService;
import com.liferay.bookmarks.uad.constants.BookmarksUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.xml.Document;
import com.liferay.portal.kernel.xml.Element;
import com.liferay.portal.kernel.xml.SAXReaderUtil;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import java.io.IOException;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the bookmarks folder UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link BookmarksFolderUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseBookmarksFolderUADExporter
	extends DynamicQueryUADExporter<BookmarksFolder> {

	@Override
	public Class<BookmarksFolder> getTypeClass() {
		return BookmarksFolder.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return bookmarksFolderLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return BookmarksUADConstants.USER_ID_FIELD_NAMES_BOOKMARKS_FOLDER;
	}

	@Override
	protected String toXmlString(BookmarksFolder bookmarksFolder)
		throws IOException {

		Document document = SAXReaderUtil.createDocument();

		Element modelElement = document.addElement("model");
		Element modelNameElement = document.addElement("model-name");

		modelNameElement.addText("com.liferay.bookmarks.model.BookmarksFolder");

		Element columnElement = modelElement.addElement("column");
		Element columnNameElement = columnElement.addElement("column-name");
		Element columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("folderId");
		columnValueElement.addText(
			String.valueOf(bookmarksFolder.getFolderId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("statusByUserId");
		columnValueElement.addText(
			String.valueOf(bookmarksFolder.getStatusByUserId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("statusByUserName");
		columnValueElement.addCDATA(bookmarksFolder.getStatusByUserName());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("userId");
		columnValueElement.addText(String.valueOf(bookmarksFolder.getUserId()));
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("userName");
		columnValueElement.addCDATA(bookmarksFolder.getUserName());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("treePath");
		columnValueElement.addCDATA(bookmarksFolder.getTreePath());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("name");
		columnValueElement.addCDATA(bookmarksFolder.getName());
		columnElement = modelElement.addElement("column");
		columnNameElement = columnElement.addElement("column-name");
		columnValueElement = columnElement.addElement("column-value");

		columnNameElement.addText("description");
		columnValueElement.addCDATA(bookmarksFolder.getDescription());

		return document.formattedString();
	}

	@Reference
	protected BookmarksFolderLocalService bookmarksFolderLocalService;

}