/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.uad.exporter;

import com.liferay.layout.uad.constants.LayoutUADConstants;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.model.Layout;
import com.liferay.portal.kernel.service.LayoutLocalService;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the layout UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link LayoutUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseLayoutUADExporter
	extends DynamicQueryUADExporter<Layout> {

	@Override
	public Class<Layout> getTypeClass() {
		return Layout.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return layoutLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return LayoutUADConstants.USER_ID_FIELD_NAMES_LAYOUT;
	}

	@Override
	protected String toXmlString(Layout layout) {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portal.kernel.model.Layout");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>plid</column-name><column-value><![CDATA[");

		String plid = String.valueOf(layout.getPlid());

		plid = StringUtil.replace(plid, "]]><", "[$SPECIAL_CHARACTER$]");
		plid = StringUtil.replace(plid, "]]>", "]]]]><![CDATA[>");
		plid = StringUtil.replace(plid, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(plid);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");

		String statusByUserId = String.valueOf(layout.getStatusByUserId());

		statusByUserId = StringUtil.replace(
			statusByUserId, "]]><", "[$SPECIAL_CHARACTER$]");
		statusByUserId = StringUtil.replace(
			statusByUserId, "]]>", "]]]]><![CDATA[>");
		statusByUserId = StringUtil.replace(
			statusByUserId, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(statusByUserId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");

		String statusByUserName = String.valueOf(layout.getStatusByUserName());

		statusByUserName = StringUtil.replace(
			statusByUserName, "]]><", "[$SPECIAL_CHARACTER$]");
		statusByUserName = StringUtil.replace(
			statusByUserName, "]]>", "]]]]><![CDATA[>");
		statusByUserName = StringUtil.replace(
			statusByUserName, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(statusByUserName);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");

		String userId = String.valueOf(layout.getUserId());

		userId = StringUtil.replace(userId, "]]><", "[$SPECIAL_CHARACTER$]");
		userId = StringUtil.replace(userId, "]]>", "]]]]><![CDATA[>");
		userId = StringUtil.replace(userId, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(userId);

		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");

		String userName = String.valueOf(layout.getUserName());

		userName = StringUtil.replace(
			userName, "]]><", "[$SPECIAL_CHARACTER$]");
		userName = StringUtil.replace(userName, "]]>", "]]]]><![CDATA[>");
		userName = StringUtil.replace(
			userName, "[$SPECIAL_CHARACTER$]", "]]><");

		sb.append(userName);

		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected LayoutLocalService layoutLocalService;

}