/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.BadColumnNameEntry;
import com.liferay.portal.tools.service.builder.test.service.BadColumnNameEntryLocalServiceUtil;

/**
 * The extended model base implementation for the BadColumnNameEntry service. Represents a row in the &quot;BadColumnNameEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BadColumnNameEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BadColumnNameEntryImpl
 * @see BadColumnNameEntry
 * @generated
 */
public abstract class BadColumnNameEntryBaseImpl
	extends BadColumnNameEntryModelImpl implements BadColumnNameEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bad column name entry model instance should use the <code>BadColumnNameEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BadColumnNameEntryLocalServiceUtil.addBadColumnNameEntry(this);
		}
		else {
			BadColumnNameEntryLocalServiceUtil.updateBadColumnNameEntry(this);
		}
	}

}