/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.BadColumnNameEntry;
import com.liferay.portal.tools.service.builder.test.model.BadColumnNameEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BadColumnNameEntry service. Represents a row in the &quot;BadColumnNameEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BadColumnNameEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BadColumnNameEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BadColumnNameEntryImpl
 * @generated
 */
public class BadColumnNameEntryModelImpl
	extends BaseModelImpl<BadColumnNameEntry>
	implements BadColumnNameEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bad column name entry model instance should use the <code>BadColumnNameEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "BadColumnNameEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"badColumnNameEntryId", Types.BIGINT}, {"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("badColumnNameEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BadColumnNameEntry (badColumnNameEntryId LONG not null primary key,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table BadColumnNameEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY badColumnNameEntry.type ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BadColumnNameEntry.type_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.BadColumnNameEntry"));

	public BadColumnNameEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _badColumnNameEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBadColumnNameEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _badColumnNameEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BadColumnNameEntry.class;
	}

	@Override
	public String getModelClassName() {
		return BadColumnNameEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BadColumnNameEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BadColumnNameEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BadColumnNameEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BadColumnNameEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BadColumnNameEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BadColumnNameEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BadColumnNameEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BadColumnNameEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BadColumnNameEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BadColumnNameEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BadColumnNameEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BadColumnNameEntry, Object>>();

			attributeGetterFunctions.put(
				"badColumnNameEntryId",
				BadColumnNameEntry::getBadColumnNameEntryId);
			attributeGetterFunctions.put("type", BadColumnNameEntry::getType);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<BadColumnNameEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BadColumnNameEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<BadColumnNameEntry, ?>>();

			attributeSetterBiConsumers.put(
				"badColumnNameEntryId",
				(BiConsumer<BadColumnNameEntry, Long>)
					BadColumnNameEntry::setBadColumnNameEntryId);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<BadColumnNameEntry, String>)
					BadColumnNameEntry::setType);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getBadColumnNameEntryId() {
		return _badColumnNameEntryId;
	}

	@Override
	public void setBadColumnNameEntryId(long badColumnNameEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_badColumnNameEntryId = badColumnNameEntryId;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalType() {
		return getColumnOriginalValue("type_");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, BadColumnNameEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BadColumnNameEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BadColumnNameEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BadColumnNameEntryImpl badColumnNameEntryImpl =
			new BadColumnNameEntryImpl();

		badColumnNameEntryImpl.setBadColumnNameEntryId(
			getBadColumnNameEntryId());
		badColumnNameEntryImpl.setType(getType());

		badColumnNameEntryImpl.resetOriginalValues();

		return badColumnNameEntryImpl;
	}

	@Override
	public BadColumnNameEntry cloneWithOriginalValues() {
		BadColumnNameEntryImpl badColumnNameEntryImpl =
			new BadColumnNameEntryImpl();

		badColumnNameEntryImpl.setBadColumnNameEntryId(
			this.<Long>getColumnOriginalValue("badColumnNameEntryId"));
		badColumnNameEntryImpl.setType(
			this.<String>getColumnOriginalValue("type_"));

		return badColumnNameEntryImpl;
	}

	@Override
	public int compareTo(BadColumnNameEntry badColumnNameEntry) {
		int value = 0;

		value = getType().compareTo(badColumnNameEntry.getType());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BadColumnNameEntry)) {
			return false;
		}

		BadColumnNameEntry badColumnNameEntry = (BadColumnNameEntry)object;

		long primaryKey = badColumnNameEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BadColumnNameEntry> toCacheModel() {
		BadColumnNameEntryCacheModel badColumnNameEntryCacheModel =
			new BadColumnNameEntryCacheModel();

		badColumnNameEntryCacheModel.badColumnNameEntryId =
			getBadColumnNameEntryId();

		badColumnNameEntryCacheModel.type = getType();

		String type = badColumnNameEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			badColumnNameEntryCacheModel.type = null;
		}

		return badColumnNameEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BadColumnNameEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BadColumnNameEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BadColumnNameEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(BadColumnNameEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BadColumnNameEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BadColumnNameEntry.class, ModelWrapper.class);

	}

	private long _badColumnNameEntryId;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BadColumnNameEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BadColumnNameEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"badColumnNameEntryId", _badColumnNameEntryId);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("badColumnNameEntryId", 1L);

		columnBitmasks.put("type_", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BadColumnNameEntry _escapedModel;

}