/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.DateTypeEntry;
import com.liferay.portal.tools.service.builder.test.model.DateTypeEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DateTypeEntry service. Represents a row in the &quot;DateTypeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DateTypeEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DateTypeEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DateTypeEntryImpl
 * @generated
 */
public class DateTypeEntryModelImpl
	extends BaseModelImpl<DateTypeEntry> implements DateTypeEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a date type entry model instance should use the <code>DateTypeEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DateTypeEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"dateTypeEntryId", Types.BIGINT}, {"dateValue", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dateTypeEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dateValue", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DateTypeEntry (dateTypeEntryId LONG not null primary key,dateValue DATE null)";

	public static final String TABLE_SQL_DROP = "drop table DateTypeEntry";

	public static final String ENTITY_ALIAS = "dateTypeEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dateTypeEntry.dateTypeEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DateTypeEntry.dateTypeEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATETYPEENTRYID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.DateTypeEntry"));

	public DateTypeEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dateTypeEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDateTypeEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dateTypeEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DateTypeEntry.class;
	}

	@Override
	public String getModelClassName() {
		return DateTypeEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DateTypeEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DateTypeEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DateTypeEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DateTypeEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DateTypeEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DateTypeEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DateTypeEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DateTypeEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DateTypeEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DateTypeEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DateTypeEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DateTypeEntry, Object>>();

			attributeGetterFunctions.put(
				"dateTypeEntryId", DateTypeEntry::getDateTypeEntryId);
			attributeGetterFunctions.put(
				"dateValue", DateTypeEntry::getDateValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DateTypeEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DateTypeEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<DateTypeEntry, ?>>();

			attributeSetterBiConsumers.put(
				"dateTypeEntryId",
				(BiConsumer<DateTypeEntry, Long>)
					DateTypeEntry::setDateTypeEntryId);
			attributeSetterBiConsumers.put(
				"dateValue",
				(BiConsumer<DateTypeEntry, Date>)DateTypeEntry::setDateValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getDateTypeEntryId() {
		return _dateTypeEntryId;
	}

	@Override
	public void setDateTypeEntryId(long dateTypeEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateTypeEntryId = dateTypeEntryId;
	}

	@Override
	public Date getDateValue() {
		return _dateValue;
	}

	@Override
	public void setDateValue(Date dateValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateValue = dateValue;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DateTypeEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DateTypeEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DateTypeEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DateTypeEntryImpl dateTypeEntryImpl = new DateTypeEntryImpl();

		dateTypeEntryImpl.setDateTypeEntryId(getDateTypeEntryId());
		dateTypeEntryImpl.setDateValue(getDateValue());

		dateTypeEntryImpl.resetOriginalValues();

		return dateTypeEntryImpl;
	}

	@Override
	public DateTypeEntry cloneWithOriginalValues() {
		DateTypeEntryImpl dateTypeEntryImpl = new DateTypeEntryImpl();

		dateTypeEntryImpl.setDateTypeEntryId(
			this.<Long>getColumnOriginalValue("dateTypeEntryId"));
		dateTypeEntryImpl.setDateValue(
			this.<Date>getColumnOriginalValue("dateValue"));

		return dateTypeEntryImpl;
	}

	@Override
	public int compareTo(DateTypeEntry dateTypeEntry) {
		long primaryKey = dateTypeEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DateTypeEntry)) {
			return false;
		}

		DateTypeEntry dateTypeEntry = (DateTypeEntry)object;

		long primaryKey = dateTypeEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DateTypeEntry> toCacheModel() {
		DateTypeEntryCacheModel dateTypeEntryCacheModel =
			new DateTypeEntryCacheModel();

		dateTypeEntryCacheModel.dateTypeEntryId = getDateTypeEntryId();

		Date dateValue = getDateValue();

		if (dateValue != null) {
			dateTypeEntryCacheModel.dateValue = dateValue.getTime();
		}
		else {
			dateTypeEntryCacheModel.dateValue = Long.MIN_VALUE;
		}

		return dateTypeEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DateTypeEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DateTypeEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DateTypeEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DateTypeEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DateTypeEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DateTypeEntry.class, ModelWrapper.class);

	}

	private long _dateTypeEntryId;
	private Date _dateValue;

	public <T> T getColumnValue(String columnName) {
		Function<DateTypeEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DateTypeEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("dateTypeEntryId", _dateTypeEntryId);
		_columnOriginalValues.put("dateValue", _dateValue);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("dateTypeEntryId", 1L);

		columnBitmasks.put("dateValue", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DateTypeEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1528183287