/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.DateTypeEntry;
import com.liferay.portal.tools.service.builder.test.service.DateTypeEntryLocalServiceUtil;

/**
 * The extended model base implementation for the DateTypeEntry service. Represents a row in the &quot;DateTypeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DateTypeEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DateTypeEntryImpl
 * @see DateTypeEntry
 * @generated
 */
public abstract class DateTypeEntryBaseImpl
	extends DateTypeEntryModelImpl implements DateTypeEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a date type entry model instance should use the <code>DateTypeEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DateTypeEntryLocalServiceUtil.addDateTypeEntry(this);
		}
		else {
			DateTypeEntryLocalServiceUtil.updateDateTypeEntry(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1274944154