/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.FilterFindEntry;
import com.liferay.portal.tools.service.builder.test.service.FilterFindEntryLocalServiceUtil;

/**
 * The extended model base implementation for the FilterFindEntry service. Represents a row in the &quot;FilterFindEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FilterFindEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FilterFindEntryImpl
 * @see FilterFindEntry
 * @generated
 */
public abstract class FilterFindEntryBaseImpl
	extends FilterFindEntryModelImpl implements FilterFindEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a filter find entry model instance should use the <code>FilterFindEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FilterFindEntryLocalServiceUtil.addFilterFindEntry(this);
		}
		else {
			FilterFindEntryLocalServiceUtil.updateFilterFindEntry(this);
		}
	}

}