/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.FilterFindEntry;
import com.liferay.portal.tools.service.builder.test.model.FilterFindEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FilterFindEntry service. Represents a row in the &quot;FilterFindEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FilterFindEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FilterFindEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FilterFindEntryImpl
 * @generated
 */
public class FilterFindEntryModelImpl
	extends BaseModelImpl<FilterFindEntry> implements FilterFindEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a filter find entry model instance should use the <code>FilterFindEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "FilterFindEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"filterFindEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"type_", Types.VARCHAR}, {"integer_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("filterFindEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("integer_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FilterFindEntry (filterFindEntryId LONG not null primary key,groupId LONG,type_ VARCHAR(75) null,integer_ INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table FilterFindEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY filterFindEntry.integer ASC, filterFindEntry.type ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FilterFindEntry.integer_ ASC, FilterFindEntry.type_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INTEGER_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.FilterFindEntry"));

	public FilterFindEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _filterFindEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFilterFindEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _filterFindEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FilterFindEntry.class;
	}

	@Override
	public String getModelClassName() {
		return FilterFindEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FilterFindEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FilterFindEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FilterFindEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FilterFindEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FilterFindEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FilterFindEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FilterFindEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FilterFindEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FilterFindEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FilterFindEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FilterFindEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<FilterFindEntry, Object>>();

			attributeGetterFunctions.put(
				"filterFindEntryId", FilterFindEntry::getFilterFindEntryId);
			attributeGetterFunctions.put(
				"groupId", FilterFindEntry::getGroupId);
			attributeGetterFunctions.put("type", FilterFindEntry::getType);
			attributeGetterFunctions.put(
				"integer", FilterFindEntry::getInteger);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<FilterFindEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FilterFindEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<FilterFindEntry, ?>>();

			attributeSetterBiConsumers.put(
				"filterFindEntryId",
				(BiConsumer<FilterFindEntry, Long>)
					FilterFindEntry::setFilterFindEntryId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<FilterFindEntry, Long>)FilterFindEntry::setGroupId);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<FilterFindEntry, String>)FilterFindEntry::setType);
			attributeSetterBiConsumers.put(
				"integer",
				(BiConsumer<FilterFindEntry, Integer>)
					FilterFindEntry::setInteger);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getFilterFindEntryId() {
		return _filterFindEntryId;
	}

	@Override
	public void setFilterFindEntryId(long filterFindEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_filterFindEntryId = filterFindEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public int getInteger() {
		return _integer;
	}

	@Override
	public void setInteger(int integer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_integer = integer;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, FilterFindEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FilterFindEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FilterFindEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FilterFindEntryImpl filterFindEntryImpl = new FilterFindEntryImpl();

		filterFindEntryImpl.setFilterFindEntryId(getFilterFindEntryId());
		filterFindEntryImpl.setGroupId(getGroupId());
		filterFindEntryImpl.setType(getType());
		filterFindEntryImpl.setInteger(getInteger());

		filterFindEntryImpl.resetOriginalValues();

		return filterFindEntryImpl;
	}

	@Override
	public FilterFindEntry cloneWithOriginalValues() {
		FilterFindEntryImpl filterFindEntryImpl = new FilterFindEntryImpl();

		filterFindEntryImpl.setFilterFindEntryId(
			this.<Long>getColumnOriginalValue("filterFindEntryId"));
		filterFindEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		filterFindEntryImpl.setType(
			this.<String>getColumnOriginalValue("type_"));
		filterFindEntryImpl.setInteger(
			this.<Integer>getColumnOriginalValue("integer_"));

		return filterFindEntryImpl;
	}

	@Override
	public int compareTo(FilterFindEntry filterFindEntry) {
		int value = 0;

		if (getInteger() < filterFindEntry.getInteger()) {
			value = -1;
		}
		else if (getInteger() > filterFindEntry.getInteger()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getType().compareTo(filterFindEntry.getType());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FilterFindEntry)) {
			return false;
		}

		FilterFindEntry filterFindEntry = (FilterFindEntry)object;

		long primaryKey = filterFindEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FilterFindEntry> toCacheModel() {
		FilterFindEntryCacheModel filterFindEntryCacheModel =
			new FilterFindEntryCacheModel();

		filterFindEntryCacheModel.filterFindEntryId = getFilterFindEntryId();

		filterFindEntryCacheModel.groupId = getGroupId();

		filterFindEntryCacheModel.type = getType();

		String type = filterFindEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			filterFindEntryCacheModel.type = null;
		}

		filterFindEntryCacheModel.integer = getInteger();

		return filterFindEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FilterFindEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FilterFindEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FilterFindEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FilterFindEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FilterFindEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FilterFindEntry.class, ModelWrapper.class);

	}

	private long _filterFindEntryId;
	private long _groupId;
	private String _type;
	private int _integer;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FilterFindEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FilterFindEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("filterFindEntryId", _filterFindEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("integer_", _integer);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");
		attributeNames.put("integer_", "integer");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("filterFindEntryId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("type_", 4L);

		columnBitmasks.put("integer_", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FilterFindEntry _escapedModel;

}