/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.FinderCachePopulationEntry;
import com.liferay.portal.tools.service.builder.test.model.FinderCachePopulationEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FinderCachePopulationEntry service. Represents a row in the &quot;FinderCachePopulationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FinderCachePopulationEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FinderCachePopulationEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinderCachePopulationEntryImpl
 * @generated
 */
public class FinderCachePopulationEntryModelImpl
	extends BaseModelImpl<FinderCachePopulationEntry>
	implements FinderCachePopulationEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a finder cache population entry model instance should use the <code>FinderCachePopulationEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "FinderCachePopulationEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"pinderCachePopulationEntryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"uniqueName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("pinderCachePopulationEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uniqueName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FinderCachePopulationEntry (pinderCachePopulationEntryId LONG not null primary key,groupId LONG,companyId LONG,uniqueName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table FinderCachePopulationEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY finderCachePopulationEntry.pinderCachePopulationEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FinderCachePopulationEntry.pinderCachePopulationEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UNIQUENAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PINDERCACHEPOPULATIONENTRYID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.FinderCachePopulationEntry"));

	public FinderCachePopulationEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _pinderCachePopulationEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPinderCachePopulationEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _pinderCachePopulationEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FinderCachePopulationEntry.class;
	}

	@Override
	public String getModelClassName() {
		return FinderCachePopulationEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FinderCachePopulationEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FinderCachePopulationEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinderCachePopulationEntry, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(FinderCachePopulationEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FinderCachePopulationEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FinderCachePopulationEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FinderCachePopulationEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FinderCachePopulationEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FinderCachePopulationEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<FinderCachePopulationEntry, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<FinderCachePopulationEntry, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<FinderCachePopulationEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FinderCachePopulationEntry, Object>>();
		Map<String, BiConsumer<FinderCachePopulationEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<FinderCachePopulationEntry, ?>>();

		attributeGetterFunctions.put(
			"pinderCachePopulationEntryId",
			FinderCachePopulationEntry::getPinderCachePopulationEntryId);
		attributeSetterBiConsumers.put(
			"pinderCachePopulationEntryId",
			(BiConsumer<FinderCachePopulationEntry, Long>)
				FinderCachePopulationEntry::setPinderCachePopulationEntryId);
		attributeGetterFunctions.put(
			"groupId", FinderCachePopulationEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FinderCachePopulationEntry, Long>)
				FinderCachePopulationEntry::setGroupId);
		attributeGetterFunctions.put(
			"companyId", FinderCachePopulationEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FinderCachePopulationEntry, Long>)
				FinderCachePopulationEntry::setCompanyId);
		attributeGetterFunctions.put(
			"uniqueName", FinderCachePopulationEntry::getUniqueName);
		attributeSetterBiConsumers.put(
			"uniqueName",
			(BiConsumer<FinderCachePopulationEntry, String>)
				FinderCachePopulationEntry::setUniqueName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getPinderCachePopulationEntryId() {
		return _pinderCachePopulationEntryId;
	}

	@Override
	public void setPinderCachePopulationEntryId(
		long pinderCachePopulationEntryId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pinderCachePopulationEntryId = pinderCachePopulationEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public String getUniqueName() {
		if (_uniqueName == null) {
			return "";
		}
		else {
			return _uniqueName;
		}
	}

	@Override
	public void setUniqueName(String uniqueName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uniqueName = uniqueName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUniqueName() {
		return getColumnOriginalValue("uniqueName");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FinderCachePopulationEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FinderCachePopulationEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FinderCachePopulationEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FinderCachePopulationEntryImpl finderCachePopulationEntryImpl =
			new FinderCachePopulationEntryImpl();

		finderCachePopulationEntryImpl.setPinderCachePopulationEntryId(
			getPinderCachePopulationEntryId());
		finderCachePopulationEntryImpl.setGroupId(getGroupId());
		finderCachePopulationEntryImpl.setCompanyId(getCompanyId());
		finderCachePopulationEntryImpl.setUniqueName(getUniqueName());

		finderCachePopulationEntryImpl.resetOriginalValues();

		return finderCachePopulationEntryImpl;
	}

	@Override
	public FinderCachePopulationEntry cloneWithOriginalValues() {
		FinderCachePopulationEntryImpl finderCachePopulationEntryImpl =
			new FinderCachePopulationEntryImpl();

		finderCachePopulationEntryImpl.setPinderCachePopulationEntryId(
			this.<Long>getColumnOriginalValue("pinderCachePopulationEntryId"));
		finderCachePopulationEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		finderCachePopulationEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		finderCachePopulationEntryImpl.setUniqueName(
			this.<String>getColumnOriginalValue("uniqueName"));

		return finderCachePopulationEntryImpl;
	}

	@Override
	public int compareTo(
		FinderCachePopulationEntry finderCachePopulationEntry) {

		long primaryKey = finderCachePopulationEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FinderCachePopulationEntry)) {
			return false;
		}

		FinderCachePopulationEntry finderCachePopulationEntry =
			(FinderCachePopulationEntry)object;

		long primaryKey = finderCachePopulationEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FinderCachePopulationEntry> toCacheModel() {
		FinderCachePopulationEntryCacheModel
			finderCachePopulationEntryCacheModel =
				new FinderCachePopulationEntryCacheModel();

		finderCachePopulationEntryCacheModel.pinderCachePopulationEntryId =
			getPinderCachePopulationEntryId();

		finderCachePopulationEntryCacheModel.groupId = getGroupId();

		finderCachePopulationEntryCacheModel.companyId = getCompanyId();

		finderCachePopulationEntryCacheModel.uniqueName = getUniqueName();

		String uniqueName = finderCachePopulationEntryCacheModel.uniqueName;

		if ((uniqueName != null) && (uniqueName.length() == 0)) {
			finderCachePopulationEntryCacheModel.uniqueName = null;
		}

		return finderCachePopulationEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FinderCachePopulationEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FinderCachePopulationEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinderCachePopulationEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FinderCachePopulationEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FinderCachePopulationEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FinderCachePopulationEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinderCachePopulationEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(FinderCachePopulationEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, FinderCachePopulationEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						FinderCachePopulationEntry.class, ModelWrapper.class);

	}

	private long _pinderCachePopulationEntryId;
	private long _groupId;
	private long _companyId;
	private String _uniqueName;

	public <T> T getColumnValue(String columnName) {
		Function<FinderCachePopulationEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FinderCachePopulationEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"pinderCachePopulationEntryId", _pinderCachePopulationEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("uniqueName", _uniqueName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("pinderCachePopulationEntryId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("uniqueName", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FinderCachePopulationEntry _escapedModel;

}