/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.SortedFinderEntry;
import com.liferay.portal.tools.service.builder.test.service.SortedFinderEntryLocalServiceUtil;

/**
 * The extended model base implementation for the SortedFinderEntry service. Represents a row in the &quot;SortedFinderEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SortedFinderEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SortedFinderEntryImpl
 * @see SortedFinderEntry
 * @generated
 */
public abstract class SortedFinderEntryBaseImpl
	extends SortedFinderEntryModelImpl implements SortedFinderEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sorted finder entry model instance should use the <code>SortedFinderEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SortedFinderEntryLocalServiceUtil.addSortedFinderEntry(this);
		}
		else {
			SortedFinderEntryLocalServiceUtil.updateSortedFinderEntry(this);
		}
	}

}