/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.SortedFinderEntry;
import com.liferay.portal.tools.service.builder.test.model.SortedFinderEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SortedFinderEntry service. Represents a row in the &quot;SortedFinderEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SortedFinderEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SortedFinderEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SortedFinderEntryImpl
 * @generated
 */
public class SortedFinderEntryModelImpl
	extends BaseModelImpl<SortedFinderEntry> implements SortedFinderEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sorted finder entry model instance should use the <code>SortedFinderEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "SortedFinderEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"sortedFinderEntryId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"groupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("sortedFinderEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SortedFinderEntry (sortedFinderEntryId LONG not null primary key,name VARCHAR(75) null,groupId LONG)";

	public static final String TABLE_SQL_DROP = "drop table SortedFinderEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY sortedFinderEntry.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SortedFinderEntry.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.SortedFinderEntry"));

	public SortedFinderEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sortedFinderEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSortedFinderEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sortedFinderEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SortedFinderEntry.class;
	}

	@Override
	public String getModelClassName() {
		return SortedFinderEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SortedFinderEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SortedFinderEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SortedFinderEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SortedFinderEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SortedFinderEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SortedFinderEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SortedFinderEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SortedFinderEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SortedFinderEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<SortedFinderEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<SortedFinderEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<SortedFinderEntry, Object>>();

			attributeGetterFunctions.put(
				"sortedFinderEntryId",
				SortedFinderEntry::getSortedFinderEntryId);
			attributeGetterFunctions.put("name", SortedFinderEntry::getName);
			attributeGetterFunctions.put(
				"groupId", SortedFinderEntry::getGroupId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<SortedFinderEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SortedFinderEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<SortedFinderEntry, ?>>();

			attributeSetterBiConsumers.put(
				"sortedFinderEntryId",
				(BiConsumer<SortedFinderEntry, Long>)
					SortedFinderEntry::setSortedFinderEntryId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<SortedFinderEntry, String>)
					SortedFinderEntry::setName);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<SortedFinderEntry, Long>)
					SortedFinderEntry::setGroupId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getSortedFinderEntryId() {
		return _sortedFinderEntryId;
	}

	@Override
	public void setSortedFinderEntryId(long sortedFinderEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sortedFinderEntryId = sortedFinderEntryId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SortedFinderEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SortedFinderEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SortedFinderEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SortedFinderEntryImpl sortedFinderEntryImpl =
			new SortedFinderEntryImpl();

		sortedFinderEntryImpl.setSortedFinderEntryId(getSortedFinderEntryId());
		sortedFinderEntryImpl.setName(getName());
		sortedFinderEntryImpl.setGroupId(getGroupId());

		sortedFinderEntryImpl.resetOriginalValues();

		return sortedFinderEntryImpl;
	}

	@Override
	public SortedFinderEntry cloneWithOriginalValues() {
		SortedFinderEntryImpl sortedFinderEntryImpl =
			new SortedFinderEntryImpl();

		sortedFinderEntryImpl.setSortedFinderEntryId(
			this.<Long>getColumnOriginalValue("sortedFinderEntryId"));
		sortedFinderEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		sortedFinderEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));

		return sortedFinderEntryImpl;
	}

	@Override
	public int compareTo(SortedFinderEntry sortedFinderEntry) {
		int value = 0;

		value = getName().compareTo(sortedFinderEntry.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SortedFinderEntry)) {
			return false;
		}

		SortedFinderEntry sortedFinderEntry = (SortedFinderEntry)object;

		long primaryKey = sortedFinderEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SortedFinderEntry> toCacheModel() {
		SortedFinderEntryCacheModel sortedFinderEntryCacheModel =
			new SortedFinderEntryCacheModel();

		sortedFinderEntryCacheModel.sortedFinderEntryId =
			getSortedFinderEntryId();

		sortedFinderEntryCacheModel.name = getName();

		String name = sortedFinderEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			sortedFinderEntryCacheModel.name = null;
		}

		sortedFinderEntryCacheModel.groupId = getGroupId();

		return sortedFinderEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SortedFinderEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SortedFinderEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SortedFinderEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SortedFinderEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SortedFinderEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SortedFinderEntry.class, ModelWrapper.class);

	}

	private long _sortedFinderEntryId;
	private String _name;
	private long _groupId;

	public <T> T getColumnValue(String columnName) {
		Function<SortedFinderEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SortedFinderEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("sortedFinderEntryId", _sortedFinderEntryId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("groupId", _groupId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("sortedFinderEntryId", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("groupId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SortedFinderEntry _escapedModel;

}